### ISSUE TITLE
Übergabe Warenkorb an Server per Post

### ISSUE THREAD

**Issue by sattlt** [Rescuecontrol-Software-UG/rdSuite#23]
export interface ICart {
    Id: number; // obsolete
    UserId: number;
    StartDate: Date;
    Items: Array<ICartItem>;
    ReasonType: string;
    Reason: string;
    Mission: number;
    MissionType: string;
    Car: ICar;
    FromWarehouse: IWarehouse;
    ToWarehouse: IWarehouse;
    public isBooked: boolean;

}

**Comment by sattlt** [comment]
json Post
[{"ReasonType":"mission","UserId":1475,"FromWarehouse":{"Id":1777,"Name":"Handlager 1","Type":2,"StockCount":false,"StockEdit":false,"GeneralNotification":false,"DeliveryNotifictaion":false,"ReStock":false,"TypeName":"Handlager"},"StartDate":"2017-03-23T22:21:29.786Z","Items":[{"ProductId":26411,"ProductName":"Einmalhandschuhe Gr. M Nitril","Count":1},{"ProductId":26422,"ProductName":"Einmalspritzen 5 ml","Count":1},{"ProductId":26414,"ProductName":"Einmalhandschuhe Gr. XL Nitril","Count":1}]}]

**Comment by rettungskontrolle** [comment]
wie hast du die Varianten für "ReasonType" alle benannt?
Müssen wir noch die einzelnen Möglichkeiten besprechen

**Comment by rettungskontrolle** [comment]
Wichtig für Donnerstag:
Wenn eine Entnahme vorgemerkt ist, wie wir das Bearbeiten übergeben ...

**Comment by sattlt** [comment]
done
