### ISSUE TITLE
Entnahmeliste Grund usw ändern ...Button beschriftung

### ISSUE THREAD

**Issue by rettungskontrolle** [Rescuecontrol-Software-UG/rdSuite#28]
Entnahmeliste Grund usw ändern ...Button beschriftung dann Besser "Entnahme fortsetzen" statt "Entnahme starten"

**Comment by sattlt** [comment]
"Entnahme starten" taucht auf, solange die Itemliste leer ist ansonsten wird die Entnahme fortgesetzt
