### ISSUE TITLE
Auswahl des Ennahmegrunds verändern

### ISSUE THREAD

**Issue by rettungskontrolle** [Rescuecontrol-Software-UG/rdSuite#41]
Um mehr Platz auf dem Smartphone zu haben bitte die UI folgendermassen verändern:
Den Button "Auftragsnummer" nach oben in die Zeile von Entnahmegrund verlagern und direkt hinter "Entnahmegrund" platzieren.
Es steht dann also dort "Entnahmegrund" und direkt dahinter der Button "Auftragsnummer".
Der "Mehr" Button rechts soll weg. dafür soll man auf den "Auftragsnummer" Button klicken können und die weiteren Entnahmegründe auswählen können.
Wählt man dann zb "Verfall", dann würde in der Zeile stehen "Entnahmegrund" und dahinter dann der Button mit Beschriftung  "Verfall".
Schwierig zu beschreiben, wenn es unklar ist, dann ruf einfach kurz an!

**Comment by sattlt** [comment]
duplicate #46
